# Server port for Render
server.port=${PORT:8080}

# Disable security temp
spring.security.enabled=false

# Datasource (Filess.io PostgreSQL via full URI)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
# HikariCP pool size to avoid "too many connections"
spring.datasource.hikari.maximum-pool-size=1


# CORS for deployed frontend
donezo-api.cors.enabled=true
donezo-api.cors.allowedOrigins=https://damlasub.github.io

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=donezo_schema