spring.application.name=donezo-api

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# PostgreSQL DB config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
logging.level.liquibase=DEBUG


# CORS
donezo-api.cors.enabled=true
donezo-api.cors.allowedOrigins=http://localhost:3000

# Logging
logging.level.root=INFO

logging.level.org.springframework.security=DEBUG


# Virtual Threads (Java 19+)
spring.threads.virtual.enabled=true

# Static Resources handling
spring.web.resources.add-mappings=false

# Spring Security JWT Resource Server configuration
spring.security.oauth2.resourceserver.jwt.authority-prefix=ROLE_
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=role

# Optional: JWT issuer URI ( helps validate issuer)
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://your-issuer-uri

# Optional: Token expiration properties (if used in your app, for token generation)
donezo-api.auth.tokenExpiration=3600000
donezo-api.auth.refreshTokenExpiration=86400000
donezo-api.auth.rounds=11
donezo-api.auth.issuer=http://localhost:8080/

# Secret key for signing (make sure to keep secret safe, don't commit real secret)
donezo-api.auth.secret=${DONEZO_API_AUTH_SECRET}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
# UI: http://localhost:8080/swagger-ui.html

# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs
# JSON spec: http://localhost:8080/api-docs