# Enable auth in prod
spring.security.enabled=true


# Simple HTTP Basic auth for prod
spring.security.user.name=${PROD_BASIC_AUTH_USERNAME}
spring.security.user.password=${PROD_BASIC_AUTH_PASSWORD}

# Datasource (Filess.io PostgreSQL via full URI)
spring.datasource.url=${PROD_DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver

# CORS for deployed frontend
donezo-api.cors.enabled=true
donezo-api.cors.allowedOrigins=https://damlasub.github.io


# Liquibase enabled
spring.liquibase.enabled=true