name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'donezo-api/**'
      - 'donezo/**'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: donezo-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current directory and list files
        run: |
          pwd
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Render (using API key secret)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -sSL https://cli.render.com/install | bash
          render login --api-key $RENDER_API_KEY

      - name: Build Docker image
        run: docker build -t donezo-api .

      - name: Deploy to Render
        env:
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DONEZO_API_AUTH_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          render services deploy srv-d2fjp86r433s73bf6d00 --image donezo-api
